var a;
document.write("Value after variable declaration is: " +a);
a = 5;
document.write("<br> Intial Value is: "  +a);
a++;
document.write("<br>Value after Increment is: " +a);
a = a + 7 ;
document.write("<br>Value after addition is: " +a);
a--;
document.write("<br>Value after Decrement is: " +a);
a = a % 3;
document.write("<br>The Remainder value is: " +a);